export const FETCH_SEARCH = "FETCH_SEARCH";
export const RECEIVE_SEARCH = "RECEIVE_SEARCH";
export const INVALIDATE_SEARCH = "INVALIDATE_SEARCH";

export const FETCH_TREND = "FETCH_TREND";
export const RECEIVE_TREND = "RECEIVE_TREND";
export const INVALIDATE_TREND = "INVALIDATE_TREND";
