export const FETCH_USER = "FETCH_USER";
export const RECEIVE_USER = "RECEIVE_USER";
export const INVALIDATE_USER = "INVALIDATE_USER";

export const FETCH_STARRED = "FETCH_STARRED";
export const RECEIVE_STARRED = "RECEIVE_STARRED";
export const INVALIDATE_STARRED = "INVALIDATE_STARRED";
